name: rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    permissions: {}
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
    - name: Enable fs-verity on /
      run: sudo tune2fs -O verity $(findmnt -vno SOURCE /)

    - uses: actions/checkout@v4

    - run: cargo build --verbose
    - run: cargo fmt --check
    - run: cargo clippy --all-targets -- -Dwarnings
    - run: cargo test
    - run: cargo publish --dry-run
